// Dark/light contrast audit (build-spec Phase 6): computes WCAG contrast for
// the token pairs components actually use, per theme, from tokens.css.
// Usage: node scripts/contrast-audit.mjs  → prints markdown (docs/contrast-audit.md)
import { readFileSync } from 'node:fs'

const css = readFileSync(new URL('../src/styles/tokens.css', import.meta.url), 'utf8')
// The low-DPI media block reuses the same selectors, so split the sheet
// first — a flat matchAll would let the overrides clobber the base blocks.
const [stdCss, lowCss = ''] = css.split('@media (max-resolution: 1.5dppx)')
const parse = (src) => {
  const blocks = {}
  for (const m of src.matchAll(
    /(:root|body\.dark|body\.theme-cobalt|body\.theme-cobalt\.dark)\s*\{([^}]*)\}/g,
  )) {
    const vars = {}
    for (const v of m[2].matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)) vars[v[1]] = v[2].trim()
    blocks[m[1]] = vars
  }
  return blocks
}
const blocks = parse(stdCss)
const low = parse(lowCss)
const compose = (extra) => ({
  'Stone light': { ...blocks[':root'], ...extra[':root'] },
  'Stone dark': {
    ...blocks[':root'],
    ...extra[':root'],
    ...blocks['body.dark'],
    ...extra['body.dark'],
  },
  'Cobalt light': {
    ...blocks[':root'],
    ...extra[':root'],
    ...blocks['body.theme-cobalt'],
    ...extra['body.theme-cobalt'],
  },
  'Cobalt dark': {
    ...blocks[':root'],
    ...extra[':root'],
    ...blocks['body.theme-cobalt'],
    ...extra['body.theme-cobalt'],
    ...blocks['body.theme-cobalt.dark'],
    ...extra['body.theme-cobalt.dark'],
  },
})
const themes = compose({})
const themesLowDpi = compose(low)
const hex = (h) => {
  const s = h.replace('#', '')
  const f =
    s.length === 3
      ? s
          .split('')
          .map((c) => c + c)
          .join('')
      : s
  return [0, 2, 4].map((i) => parseInt(f.slice(i, i + 2), 16) / 255)
}
const lum = (rgb) => {
  const [r, g, b] = rgb.map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4))
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}
const ratio = (a, b) => {
  const [l1, l2] = [lum(hex(a)), lum(hex(b))].sort((x, y) => y - x)
  return (l1 + 0.05) / (l2 + 0.05)
}
// [foreground, background, where it is used, minimum we hold it to]
const PAIRS = [
  ['ink', 'bg', 'body text, titles', 4.5],
  ['ink-soft', 'bg', 'running prose, key-values', 4.5],
  ['muted', 'bg', 'secondary UI text (12–13px)', 4.5],
  ['faint', 'bg', 'micro-labels, dense metadata (11px) — decorative/secondary', 3],
  ['muted', 'bg-subtle', 'story card text, rail body', 4.5],
  ['faint', 'bg-subtle', 'docs line, timestamps on subtle ground', 3],
  ['success', 'success-bg', 'populated pill, extracted badge', 4.5],
  ['warn', 'warn-bg', 'review required chip, conf low, flags', 4.5],
  ['warn', 'bg', 'flag line, unresolved text', 4.5],
  ['error', 'error-bg', 'error banner / toast', 4.5],
  ['indigo', 'indigo-bg', 'deal chips, via tier2', 4.5],
  ['indigo', 'bg', 'attention heading, section links', 4.5],
  ['on-ink', 'primary', 'primary button label', 4.5],
  ['rail-fg', 'rail-bg', 'rail items', 4.5],
  ['rail-fg-muted', 'rail-bg', 'rail icons, section numbers, zone heading', 3],
  ['rail-active-fg', 'rail-active-bg', 'active rail item', 4.5],
]
const lines = [
  '# Contrast audit',
  '',
  'Generated by `node scripts/contrast-audit.mjs` from `src/styles/tokens.css`. WCAG 2.x contrast ratios for the token pairs components use; "min" is the bar each pair is held to (4.5:1 for text, 3:1 for large/decorative text and UI glyphs). ✗ marks a pair below its bar.',
  '',
]
const failures = []
const emitTable = (set, label) => {
  lines.push('| Pair | Used for | Min | ' + Object.keys(set).join(' | ') + ' |')
  lines.push(
    '|---|---|---|' +
      Object.keys(set)
        .map(() => '---')
        .join('|') +
      '|',
  )
  for (const [fg, bg, use, min] of PAIRS) {
    const cells = Object.entries(set).map(([name, t]) => {
      const r = ratio(t[fg], t[bg])
      const ok = r >= min
      if (!ok) failures.push(`${label}${name}: --${fg} on --${bg} = ${r.toFixed(2)} (min ${min})`)
      return `${r.toFixed(2)}${ok ? '' : ' ✗'}`
    })
    lines.push(`| \`--${fg}\` on \`--${bg}\` | ${use} | ${min} | ${cells.join(' | ')} |`)
  }
}
emitTable(themes, '')
lines.push(
  '',
  '## Low-DPI effective values',
  '',
  'The `@media (max-resolution: 1.5dppx)` block darkens `--rule`/`--rule-strong` one step and nudges `--muted`/`--faint` for uncalibrated standard-DPI panels. Ratios with those overrides applied:',
  '',
)
emitTable(themesLowDpi, 'low-DPI ')
lines.push('', '## Below the bar', '')
lines.push(...(failures.length ? failures.map((f) => `- ${f}`) : ['- none']))
console.log(lines.join('\n'))
