/**
 * ALL user-facing copy lives in this file — nav names, screen titles and
 * subtitles, button labels, hints and placeholders, empty states, toasts,
 * micro-labels, the disclaimer. Components never carry their own words, so
 * changing wording never requires opening a component file.
 *
 * How to edit safely (see docs/editing-copy.md for the full map):
 *  - Change only the text between the quotes. Keep the quotes, keep the
 *    trailing commas.
 *  - Pieces in {curly braces} like '{n}' or '{owner}' are fill-ins the app
 *    replaces at runtime (a count, a name, a date). Keep them — you may move
 *    them within the sentence, but don't delete or rename them.
 *  - Where wording differs by count there is a pair: `...One` is used for
 *    exactly one, `...Other` for any other number.
 *
 * Naming note: the left-nav items ("My reviews", "All reviews") and the
 * context-rail tab names ("Why", "Respond", "Debate", "Prior") are
 * placeholders pending the naming workshop — rename them right here.
 */
export const strings = {
  /* ════════ Shared bits used on several screens ════════ */
  common: {
    pageRef: 'p. {n}', // the mono page reference on quotes, items, and search hits
  },

  /* ════════ Masthead & app chrome ════════ */
  app: {
    brand: 'Sentinel',
    healthReady: 'ready',
    skipToContent: 'Skip to content',
    dismissToast: 'Dismiss',
  },
  theme: {
    selectLabel: 'Theme',
    stone: 'Stone',
    cobalt: 'Cobalt',
    toggleDark: 'Toggle dark mode',
    textSizeLabel: 'Text size',
    textSizeS: 'S',
    textSizeM: 'M',
    textSizeL: 'L',
    textSizeSmall: 'Small text',
    textSizeMedium: 'Medium text (default)',
    textSizeLarge: 'Large text',
  },

  /* ════════ Shared borrower-group document anatomy ════════ */
  docGroups: {
    docsOne: '1 document',
    docsOther: '{n} documents',
  },

  /* ════════ Shared upload rows (per-file progress + named-rule rejection) ════════ */
  upload: {
    overLimit: '{size} MB — over the {limit} MB limit',
    wrongType: 'not a supported file type here',
    remove: 'Remove',
  },

  /* ════════ Command palette (⌘K) ════════ */
  palette: {
    trigger: 'Search',
    triggerAria: 'Search everything',
    triggerTitle: 'Search — ⌘K',
    placeholder: 'Search borrowers, RXM, documents — or type a command…',
    inputAria: 'Search everything',
    groupReviews: 'Reviews',
    groupDocuments: 'Documents',
    groupActions: 'Actions',
    kbdEsc: 'esc',
    navigate: 'navigate',
    open: 'open',
    close: 'close',
    empty: 'Nothing matches — try a borrower name, an RXM, or a command.',
    actStartReview: 'Start a review',
    actStartAnalysis: 'Start a portfolio analysis',
    actAllReviews: 'All reviews',
    actCrrDocuments: 'Documents (CRR)',
    actCpeaRuns: 'Runs (CPEA)',
    actPolicy: 'Policy search',
    statusInProgress: '{n} open',
    statusReady: 'completed',
  },

  /* ════════ Suite landing + application switcher ════════ */
  suite: {
    apps: {
      /* Descriptions are single-line Steve-drafts — wordsmithing later. */
      crr: {
        short: 'CRR',
        full: 'Credit Risk Review',
        description: 'Deep-dive credit review files, purpose-built for CRR.',
      },
      /* Renamed 2026-09-18 (refinement round); routes stay /erm — the
         rename is presentation. */
      erm: {
        short: 'CPEA',
        full: 'Credit Portfolio Event Assessment',
        description: 'Portfolio-level insights and analysis.',
      },
      vantage: {
        short: 'Vantage',
        full: 'P&C',
        description: 'Generic document extraction and insights.',
      },
    },
    landingAria: 'Applications',
    open: 'Open',
    inDesign: 'In design',
    allApplications: 'All applications',
    switcherAria: 'Switch application',
    currentApp: 'Current application',
    fictionalNote: 'All data in this demonstration build is fictional.',
  },

  /* ════════ ERM application (start · processing · results · runs · documents) ════════ */
  erm: {
    nav: {
      home: 'Home',
      runs: 'Runs',
      documents: 'Documents',
      aria: 'Credit Portfolio Event Assessment navigation',
    },
    start: {
      title: 'Start a portfolio analysis',
      sub: 'Ask a question of any population — documents you bring, documents on system, or a whole portfolio slice.',
      questionZone: 'What to ask',
      questionAside: 'one prompt, or a saved question set',
      modeAria: 'Question mode',
      modePrompt: 'Prompt only',
      modeQset: 'Question set',
      addNew: 'Add new',
      addNewHint: '· upload a question set',
      qsCardCount: '{n} questions',
      /* Add-a-question-set modal */
      qsModalTitle: 'Add a question set',
      qsModalClose: 'Close',
      qsDropTitle: 'Drop a question file here',
      qsDropHint: 'or browse files · CSV or XLSX, one question per row',
      qsDropAria: 'Upload a question file',
      qsTitleLabel: 'Title',
      qsTitlePlaceholder: 'e.g. Watchlist deep-dive',
      qsDescLabel: 'Description',
      qsDescPlaceholder: 'One line on what this set asks and when to use it',
      qsSave: 'Save',
      qsCancel: 'Cancel',
      promptAria: 'Prompt',
      promptPlaceholder:
        'What do you want to know? e.g. Which borrowers have covenant headroom below 1.0x at the latest test?',
      documentsZone: 'The documents',
      documentsAside: 'optional — leave empty to run on the population below',
      dropTitle: 'Drop documents here',
      dropBrowse: 'or browse files · or',
      dropRepo: 'select from the repository',
      dropAria: 'Upload documents',
      populationZone: 'The population',
      populationAside: 'full-population search — scope resolved on system',
      /* The dropdown VOCABULARY below the labels is a deliberate placeholder
         (ratified 2026-09-18): the shape is the design; the words are not. */
      popPortfolio: 'Portfolio',
      popSubPortfolio: 'Sub-portfolio',
      popRegion: 'Region',
      popAsOf: 'As of',
      scopeLine: 'Will run against: {scope} — resolves to {borrowers} · {documents}',
      borrowersOne: '1 borrower',
      borrowersOther: '{n} borrowers',
      run: 'Run analysis',
      attached: '{files} attached',
      filesOne: '1 file',
      filesOther: '{n} files',
    },
    processing: {
      title: 'Running the analysis',
      sub: '{set} · {questions} questions · {scope} — {borrowers}, {documents}.',
      leave: 'You can leave — the run continues and lands in Runs.',
      cancel: 'Cancel run',
      stepPopulation: 'Population resolved',
      stepPopulationMeta: '{borrowers} · {documents}',
      stepIndex: 'Document index current',
      stepIndexMeta: 'no re-parsing needed',
      stepQuestions: 'Running {questions} questions across {documents} documents',
      stepQuestionsMeta: '{done} of {total}',
      stepComputing: 'Computing status & materiality',
    },
    results: {
      title: 'Portfolio monitor',
      sub: 'Run {state} {time} · {set} · {portfolio} — one row per borrower, every answer match-rated.',
      stateCompleted: 'completed',
      stateCancelled: 'cancelled',
      stateFailed: 'failed',
      newAnalysis: 'New analysis',
      exportExcel: 'Export summary (Excel)',
      exportWord: 'Export summary (Word)',
      exportNotReady: 'Export is not wired in this build — the Excel-vs-Word ruling is still open.',
      cancelledNote:
        'This run was cancelled before completion — no answers were recorded. The run is kept here as a record.',
      summary: 'Summary',
      setChip: '{name} · {n} questions',
      runLine: 'run {time} · {portfolio} · {asOf}',
      countsLine: '{borrowers} analyzed · {documents} · {questions} questions · {answers} answers',
      questionsOne: '1 question',
      questionsOther: '{n} questions',
      answersOne: '1 answer',
      answersOther: '{n} answers',
      chipStated: '{n} stated',
      chipDerived: '{n} derived',
      chipUnsupported: '{n} unsupported',
      attention: 'Most attention needed: ',
      attentionLine: '{name} — {flags} of {total} answers unsupported',
      popSummary: 'Population — why these borrowers',
      popCounts: '{included} included · {excluded} excluded · {indeterminate} indeterminate',
      popCriteria:
        'Criteria: {portfolio} · {sub} · {region} · {asOf}. Exclusions are named, never silent:',
      groupByAria: 'Group results',
      byBorrower: 'By borrower',
      byQuestion: 'By question',
      colBorrower: 'Borrower',
      colRxm: 'RXM',
      colFlags: 'Flags',
      flagsBadge: '{n} unsupported',
      derivedTitle: 'Derived from stated inputs — expand for the derivation',
      tableNote:
        '{shown} of {total} columns shown — expand a row for every answer · default sort: most flags first · column picker TBD',
      qBlockIndex: 'Q{n} of {total}',
      qMoreNote: 'Every answer opens the same detail-and-evidence modal.',
      expansionFooter:
        'Grades are per answer: stated (quote passes entailment) · derived (computed from stated inputs) · unsupported (nothing grounds it)',
      detailLink: 'Detail & evidence →',
      confChip: 'conf {level}',
      confHigh: 'high',
      confMedium: 'medium',
      confLow: 'low',
      toTop: 'Top',
    },
    runs: {
      title: 'Runs',
      sub: "Every analysis, kept — open any prior run's results exactly as they stood.",
      scopeLine: '{criteria} — {borrowers} · {documents}',
      viewResults: 'View results',
      today: 'Today {time}',
      stateCancelled: 'cancelled',
      stateFailed: 'failed',
      stateRunning: 'running',
      empty: 'No runs yet — start one from Home.',
    },
    documents: {
      title: 'Documents',
      sub: 'Everything on system this application can see — search it, and choose what feeds the monitor.',
      searchPlaceholder: 'Search by borrower / counterparty name or RXM',
      searchAria: 'Search documents',
      hint: '{documents} · {borrowers} on system for this application — click a borrower to expand',
      docsOne: '1 document',
      docsOther: '{n} documents',
      borrowersOne: '1 borrower',
      borrowersOther: '{n} borrowers',
      inScope: 'in monitor scope',
      notInScope: 'not in scope',
      viewExtraction: 'View extraction',
      rawDocument: 'Raw document',
      groupDocsOne: '1 document',
      groupDocsOther: '{n} documents',
      empty: 'No documents match. Try a borrower / counterparty name or RXM.',
    },
    /* Rationale-card LABELS are per-application config; these two are ERM's. */
    detail: {
      titleAnswer: '{borrower} — {label} {value}',
      answer: 'Answer',
      rationale: 'Rationale',
      memoFacts: 'Memo facts',
      basis: 'Basis',
      evidence: 'Evidence ({n})',
      viewSource: 'View source →',
      limitations: 'Limitations',
      context: 'context: sections',
      contextTitle: 'How much of the document the model saw',
      confidence: 'confidence: {level}',
      gradeChip: '{grade}',
      close: 'Close',
    },
    rawViewer: {
      title: '{file} — raw document',
      close: 'Close',
      pageLabel: 'p. {n} · page render (placeholder)',
      pagesShown: 'Showing {shown} of {total} pages',
      noPages: 'No page images are on system for this document — the extraction remains available.',
      provenance: 'page image',
    },
    picker: {
      title: 'Select from the repository',
      close: 'Close',
      searchPlaceholder: 'Search by borrower / counterparty name or RXM',
      searchAria: 'Search the repository',
      countOne: '1 document on system',
      countOther: '{n} documents on system',
      select: 'Select',
      selected: 'Selected',
      done: 'Attach {n}',
      cancel: 'Cancel',
      empty: 'Nothing matches. Try a borrower / counterparty name or RXM.',
    },
  },

  /* ════════ Vantage application (ask · processing · answer · runs) ════════ */
  vantage: {
    nav: { ask: 'Ask', runs: 'Runs', aria: 'Vantage navigation' },
    ask: {
      title: 'Ask your documents.',
      sub: 'Bring the documents, ask the question. The answer comes back in whatever shape fits — with its sources attached.',
      documentsZone: 'Documents',
      documentsAside: 'upload only — what you bring is what gets read',
      dropTitle: 'Drop documents here',
      dropBrowse: 'or browse files',
      dropHint: 'PDF · DOCX · XLSX · CSV — questions run against text and data alike',
      dropAria: 'Upload documents',
      questionZone: 'Your question',
      questionAside: 'one question — the answer is a run, not a chat',
      questionAria: 'Your question',
      askBtn: 'Ask',
      attachedOne: '1 document attached',
      attachedOther: '{n} documents attached',
    },
    processing: {
      title: 'Reading the documents',
      leave: 'This usually takes under a minute. You can leave — the answer lands in Runs.',
      cancel: 'Cancel',
    },
    answer: {
      newQuestion: '← New question',
      runLine: 'Run · {when} ·',
      viewInRuns: 'view in Runs',
      eyebrow: 'Answer',
      viewSource: 'View source',
      viewRows: 'View rows used',
      rowsLoc: 'rows {rows} of {of}',
      followupPlaceholder: 'Ask another question of these documents…',
      followupAria: 'Ask another question',
      followupAsk: 'Ask',
      followupNote:
        'Runs as a new question against the same {documents} — every answer is its own run.',
      docOne: 'document',
      docOther: '{n} documents',
      absenceHeading: 'Not in these documents',
      unknownBlock: "This answer contains a content type this version can't display.",
      unknownBlockLabel: 'Unsupported content',
      cancelledNote:
        'This run was cancelled before an answer was produced. The run is kept here as a record.',
    },
    runs: {
      title: 'Runs',
      sub: "Every question you've asked — the documents, the question, and the answer, frozen as of that moment.",
      docsChipOne: '1 document',
      docsChipOther: '{n} documents',
      answered: 'answered',
      cancelled: 'cancelled',
      failed: 'failed',
      running: 'running',
      empty: 'No runs yet — ask your first question from Ask.',
      today: 'today {time}',
      yesterday: 'yesterday',
    },
    rowsViewer: {
      title: 'Rows used — {file}',
      close: 'Close',
      loc: 'rows {rows} of {of}',
      badge: 'verbatim rows',
      rowCol: 'row',
      provenanceLabel: 'Provenance',
      provenance: 'the rows exactly as they appear in the file, untransformed.',
    },
  },

  /* ════════ Left rail (app navigation) ════════ */
  nav: {
    appNavAria: 'App navigation',
    home: 'Home',
    myReviews: 'My reviews',
    allReviews: 'All reviews',
    documents: 'Documents',
    policyLibrary: 'Policy library',
    overview: 'Overview',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
  },

  /* ════════ Landing — Start a review (/) ════════ */
  landing: {
    eyebrow: 'Credit analysis',
    title: 'Start a review',
    sub: 'Drop the documents for one borrower. Sentinel reads them, runs the policy checks, and assembles the work paper.',
    dropBig: 'Drag documents here',
    dropOr: 'or',
    browse: 'browse files',
    dropHint: 'PDF · one borrower per review',
    dropAria: 'Upload documents',
    chooseFilesAria: 'Choose PDF files',
    fileListAria: 'Documents to review',
    pickedListAria: 'Documents from the repository',
    removeFile: 'Remove file',
    contextLabel: 'Anything Sentinel should know?',
    optional: 'optional',
    contextPlaceholder:
      'Context or questions, one per line — e.g. Focus on covenant headroom. What is revolver availability at close?',
    begin: 'Begin review',
    documentCountOne: '1 document',
    documentCountOther: '{n} documents',
    fromRepo: 'or pull from the repository',
    beginCount: 'Begin review · {documents}',
    /* Workpaper configuration (option vocabulary is a deliberate placeholder
       — see screens/landing/config.ts). */
    wpcSummary: 'Workpaper configuration',
    wpcHint: 'defaults applied — open to adjust',
    wpcTemplate: 'Template',
    wpcSections: 'Sections',
    wpcTopics: 'Custom analysis topics',
    wpcTopicsPlaceholder: 'Add a topic — appends to the template, never replaces',
    recent: 'Recent',
    noRecents: 'Your reviews will appear here once you start one.',
    newReview: 'New review — reading…',
    openBadge: '{n} open',
    sectionsComplete: '{n}/6 sections',
  },

  /* ════════ Processing state of /review/:id ════════ */
  /* (The cycling status line itself comes from the backend — in demo mode,
     edit it in src/api/mock/mockApi.ts › MESSAGES.) */
  processing: {
    title: 'Reading the documents',
    away: 'This usually takes a few minutes. You can leave — the review will be waiting in your recents.',
    cancel: 'Cancel this review',
    cancelled: 'This review was cancelled.',
    failedEyebrow: 'Processing failed',
    startAnother: 'Start another review',
  },

  /* ════════ Review page (/review/:id) ════════ */
  review: {
    loading: 'Opening the review…',
    exportReview: 'Export Review',
    exporting: 'Exporting…',
    exported: 'Exported {fileName}',
    addDocument: 'Add document',
    /* evidence manifest ("Documents in this review") */
    manifestHeading: 'Documents in this review',
    manifestRun: '{n} · run completed {time}',
    manifestAmended: '{n} · evidence amended {time}',
    manifestAmendedRunning: '{n} · evidence amended {time} · impacted checks re-running',
    manifestOpening: 'opening set',
    manifestAdded: 'added mid-review · {time}',
    manifestPreview: 'Preview',
    /* "Add document" (amend evidence) modal */
    addDoc: {
      title: 'Add a document to this review',
      close: 'Close',
      tabUpload: 'Upload new',
      tabRepo: 'From the repository',
      dropTitle: 'Drop a document here',
      dropBrowse: 'or browse files',
      dropHint: "PDF · DOCX · XLSX — added to this review's evidence",
      dropAria: 'Upload a document',
      searchPlaceholder: 'Search by borrower / counterparty name or RXM',
      searchAria: 'Search the repository',
      hitOne: '1 document on system for {rxm} not yet in this review',
      hitOther: '{n} documents on system for {rxm} not yet in this review',
      uploaded: 'Uploaded {date}',
      pagesParsed: '{n} pages · parsed',
      select: 'Select',
      selected: 'Selected',
      whyLabel: 'Why is this document being added?',
      whyNote: "— recorded in the review's evidence log",
      whyPlaceholder:
        'e.g. Credit officer provided the June compliance certificate after the review opened',
      cancel: 'Cancel',
      confirm: 'Add to review',
    },
    storyHeading: 'The story',
    storyAside: 'what the documents say is going on',
    priorArrow: 'prior {prior} → current {current}',
    attentionHeading: 'Needs your attention',
    openBadge: '{n} open',
    reviewedTally: '{n} reviewed',
    attentionEmpty:
      'Nothing needs your attention. Every value was read above the confidence floor and no flags were raised.',
    sectionLink: 'Section {n} →',
    reviewRequired: 'review required',
    reviewRequiredMark: '⚠ review required',
    unresolved: 'unresolved',
    question: 'question',
    reviewedNote: 'Reviewed — "{note}"',
    reviewedPlain: 'Reviewed',
    dismissed: 'Dismissed',
    workpaperHeading: 'Work paper',
    workpaperAside: '6 sections · {n} populated',
    populated: 'populated',
    notPopulated: 'not yet populated',
    reviewReqChip: '{n} review req.',
    unresolvedChip: '{n} unresolved',
    flagLine: 'Read below the OCR confidence floor — the Word export flags this value.',
    unresolvedText: 'No content extracted for this concept.',
    reasoningStubbed: 'reasoning stubbed',
    verdict: 'Verdict: {verdict}',
    verdictNone: '—',
    snippets: '{n} retrieved snippet(s)',
    viewSource: 'View source',
    reRunning: 're-running…',
    verified: 'verified',
    clearedChip: 'cleared — {reason} · struck on screen, omitted from the exported review',
    notApplicable: 'not applicable',
    incorrect: 'incorrect',
    disclaimer: 'This tool augments your analysis; it is not the system of record.',
    /* — Areas of assessment (the management-summary verdicts) — */
    areasHeading: 'Areas of assessment',
    areasPendingBadge: '{n} pending',
    areasCount: '{n} areas',
    areasTallySat: '{n} satisfactory',
    areasTallyUnsat: '{n} unsatisfactory',
    areasTallyNa: '{n} n/a',
    ratingSatisfactory: 'satisfactory',
    ratingUnsatisfactory: 'unsatisfactory',
    ratingNa: 'n/a',
    ratingPending: 'pending',
    supportingLink: 'Supporting: Section {n} →',
    resolveLink: 'Resolve in Section {n} →',
    thenSet: 'then set:',
    setSatisfactory: 'Satisfactory',
    setUnsatisfactory: 'Unsatisfactory',
    /* — Reference data disclosure — */
    refData: 'Reference data',
    refDataMeta: 'upstream · as of {date}',
    refUpstream: 'upstream',
    refCrr: 'CRR',
  },

  /* ════════ Attention row actions (on the review page) ════════ */
  attention: {
    dismiss: 'dismiss',
    dismissAria: 'Dismiss flag: {title}',
    markReviewed: 'mark reviewed',
    markReviewedAria: 'Mark reviewed: {title}',
    edit: 'edit',
    editAria: 'Edit note: {title}',
    unreview: 'un-review',
    unreviewAria: 'Un-review: {title}',
    notePlaceholder: 'What you checked, in a line',
    noteLabel: 'Review note',
    save: 'Save',
    cancel: 'Cancel',
  },

  /* ════════ Right context rail (review page) ════════ */
  contextRail: {
    header: 'Context',
    toggle: 'Toggle context rail',
    resizeHandle: 'Resize context rail',
    resizeHint: 'Drag to resize · double-click to reset',
    noSelection: 'No item selected',
    emptyBody: 'Select a work paper item to see how it got here.',
    tabs: {
      why: 'Why',
      respond: 'Respond',
      debate: 'Debate',
      prior: 'Prior',
    },
  },
  rail: {
    selectItem: 'Select this item',
    readOnly:
      'Read-only — this review belongs to {owner}. Open it to read; editing stays with its owner.',
    howHeading: 'How this got here',
    policiesHeading: 'Applied policies & standards',
    viewStandard: 'View standard',
    viewPolicy: 'View policy',
    noPolicies: 'No policy or standard cited this item.',
    whyNote:
      'Every output shows its reasoning chain and the standards it was held to — the same trail the export and the audit record carry.',
    respondHeading: 'Respond to Sentinel',
    respondPlaceholder:
      'Correct the value, add context, or say what to re-check — Sentinel re-runs this item with your direction.',
    sendRerun: 'Send & re-run',
    markVerified: 'Mark verified',
    respondedNote: 'Sent: “{note}”',
    clearHeading: 'Clear from workpaper',
    notApplicable: 'Not applicable',
    incorrect: 'Incorrect',
    cleared: 'cleared',
    undo: 'undo',
    cancel: 'Cancel',
    rationaleLabel: 'Clear rationale',
    rationalePlaceholder: 'Why — one line, recorded with the clear',
    rationaleRequired: 'Add a one-line rationale — it is recorded with the clear.',
    confirmClear: 'Clear — {reason}',
    clearNote:
      'Cleared content stays on screen — struck through, with your rationale beside it — so the QC trail is visible while you work. The exported review simply renders without it. Nothing is silently deleted.',
    advocate: 'Advocate',
    dissent: 'Dissent',
    cites: 'cites: {citations}',
    debateNote:
      'Positions are advisory. The analyst’s disposition decides — and both positions ride into the review record.',
    debateEmpty: 'No advocate or dissent positions were produced for this item.',
    sinceHeading: 'Since the {date} review',
    openPrior: 'Open the {date} review',
    priorNote:
      'Shown only when the borrower has prior reviews. The story’s timeline covers what changed within this run’s documents; this tab covers what changed between reviews.',
    noSelectionBody: 'Select a work paper item to see how it got here.',
  },

  /* ════════ Source modal (evidence viewer) ════════ */
  source: {
    title: 'Evidence — {section}',
    close: 'Close',
    page: 'page {n}',
    sectionImage: 'section image',
    pageImage: 'page image',
    imageAria: 'Source image',
    noImage:
      'The source image isn’t available for this passage. The quote above is the extracted text.',
  },

  /* ════════ Reviews list (/reviews, /reviews/all) ════════ */
  reviews: {
    title: 'Reviews',
    tabs: { my: 'My', all: 'All' },
    searchPlaceholder: 'Search by borrower / counterparty name or RXM',
    searchAria: 'Search reviews',
    lobAria: 'Line of business',
    allLobs: 'All lines of business',
    ownerAria: 'Owner',
    allOwners: 'All owners',
    periodAria: 'Period',
    period12m: 'Last 12 months',
    periodAll: 'All time',
    countOne: '1 review · showing most recent',
    countOther: '{n} reviews · showing most recent',
    readOnlyNote: 'Team view — open any review to read it; editing stays with its owner.',
    you: 'you',
    readOnly: 'read-only',
    repeat: '{ordinal} in 12 mo',
    processingAria: 'Processing',
    emptyMy: 'Your reviews will appear here once you start one.',
    emptyAll: 'No reviews match. Try a borrower / counterparty name or RXM.',
  },
  /* Short line-of-business tags shown on list rows. */
  lobShort: {
    'IB Lending': 'IB',
    'Wealth Management': 'WM',
    'Counterparty Credit Risk': 'CCR',
  } as Record<string, string>,

  /* ════════ Documents (/documents) ════════ */
  documents: {
    eyebrow: 'Document repository',
    title: 'Documents',
    sub: 'Search everything Sentinel has read — every document, every parsed passage.',
    searchPlaceholder: 'Search by borrower / counterparty name or RXM — or any keyword',
    searchAria: 'Search documents',
    lobAria: 'Line of business',
    allLobs: 'All lines of business',
    counterpartyAria: 'Counterparty',
    allCounterparties: 'All counterparties',
    docTypeAria: 'Document type',
    allTypes: 'All types',
    advanced: 'Advanced search',
    advancedHelp: [
      ['"quoted phrase"', 'must appear verbatim'],
      ['-word', 'excludes passages containing it'],
      ['bare words', 'match any, by stem — more matches rank higher'],
    ] as ReadonlyArray<readonly [string, string]>,
    countLine: '{passages} in {documents} · {order}',
    passagesOne: '1 passage',
    passagesOther: '{n} passages',
    documentsOne: '1 document',
    documentsOther: '{n} documents',
    orderRelevance: 'sorted by relevance',
    orderRecent: 'most recent first',
    extracted: 'extracted',
    notExtracted: 'not yet extracted',
    browseHint:
      '{documents} · {borrowers} — click a borrower to expand · keyword queries still search every parsed passage',
    borrowersOne: '1 borrower',
    borrowersOther: '{n} borrowers',
    rawAction: 'Raw document',
    selectDocAria: 'Select document: {fileName}',
    previewAction: 'Preview extracted text',
    previewUnavailable: 'Available once extraction completes',
    downloadAction: 'Download original',
    downloaded: 'Downloaded {fileName}',
    previewTitle: '{fileName} — extracted text',
    previewPagesOne: '1 page',
    previewPagesOther: '{n} pages',
    previewParsed: 'parsed {date}',
    previewSectionsOne: '1 section',
    previewSectionsOther: '{n} sections',
    pageRange: 'pp. {start}–{end}',
    counterpartyPill: 'Counterparty · {name}',
    typePill: 'Type · {type}',
    viewSource: 'View source',
    usedIn: 'Used in {borrower} review →',
    empty: 'No passages match. Loosen a filter, or try different words.',
  },

  /* ════════ Policy search (/policy) ════════ */
  policy: {
    eyebrow: 'Policy library',
    title: 'Policy search',
    sub: 'Ask a question of the policies pulled into the application — or search and browse them directly.',
    searchPlaceholder:
      "Ask anything — 'When must valuation inputs be re-verified?' — or search by number, title, keyword",
    searchAria: 'Ask or search policies',
    ask: 'Ask',
    answerLabel: 'Answer',
    capabilityPreview: 'capability preview',
    revised: 'rev. {date}',
    viewPolicy: 'View policy',
    browseHeading: 'Browse policies',
    browseAside: 'newest revision first',
    view: 'View',
    empty: 'No policies match — try a number, a word from the title, or ask a question.',
    disclaimer: 'All policy content in this demonstration build is fictional.',
    viewNotReady: 'Policy text viewing is not wired in this build.',
  },

  /* ════════ Render-error screen (route error boundary) ════════ */
  errorScreen: {
    eyebrow: 'Something broke',
    title: 'This screen failed to render',
    intro: 'The error below is shown verbatim — include it if you report this.',
    back: 'Back to My reviews',
  },

  /* ════════ Not found ════════ */
  notFound: {
    title: 'Nothing here',
    body: 'That address does not match a screen in Sentinel.',
    home: 'Back to Start a review',
  },
} as const
